Notebook to ensure that there is no overlap between the test datasets and the three most common databases: IEDB, McPas-TCR, and VDJdb

In [1]:
import pandas as pd

# Load Data
## Test data
This requires the datasets to be downloaded and proccessed in advance.

In [4]:
path_viral = '../tcr_benchmark/data/viral.csv'
path_mutations = '../tcr_benchmark/data/mutation.csv'

In [77]:
df_viral = pd.read_csv(path_viral, index_col=0)
df_viral.head()

,CDR3_alpha,CDR3_beta,V_alpha,V_beta,J_alpha,J_beta,Epitope,clone_id,MHC
0,CAVNAPTGTASKLTF,CASSMRSAVEQYF,TRAV8-1*01,TRBV19*01,TRAJ44*01,TRBJ2-7*01,GILGFVFTL,25.0,HLA-A*02:01
1,CAVEGSQGNLIF,CASSMRSAVEQYF,TRAV2*01,TRBV19*01,TRAJ42*01,TRBJ2-7*01,GILGFVFTL,27.0,HLA-A*02:01
2,CAGWPGSSNTGKLIF,CASSIRSLAEQYF,TRAV25*01,TRBV19*01,TRAJ37*01,TRBJ2-7*01,GILGFVFTL,34.0,HLA-A*02:01
3,CAVRDAILTGGGNKLTF,CASRRQGITETQYF,TRAV3*01,TRBV27*01,TRAJ10*01,TRBJ2-5*01,GILGFVFTL,35.0,HLA-A*02:01
4,CATEDNDMRF,CASSFSDTQYF,TRAV17*01,TRBV5-4*01,TRAJ43*01,TRBJ2-3*01,YVLDHLIVV,39.0,HLA-A*02:01

In [78]:
df_viral

,CDR3_alpha,CDR3_beta,V_alpha,V_beta,J_alpha,J_beta,Epitope,clone_id,MHC
0,CAVNAPTGTASKLTF,CASSMRSAVEQYF,TRAV8-1*01,TRBV19*01,TRAJ44*01,TRBJ2-7*01,GILGFVFTL,25.0,HLA-A*02:01
1,CAVEGSQGNLIF,CASSMRSAVEQYF,TRAV2*01,TRBV19*01,TRAJ42*01,TRBJ2-7*01,GILGFVFTL,27.0,HLA-A*02:01
2,CAGWPGSSNTGKLIF,CASSIRSLAEQYF,TRAV25*01,TRBV19*01,TRAJ37*01,TRBJ2-7*01,GILGFVFTL,34.0,HLA-A*02:01
3,CAVRDAILTGGGNKLTF,CASRRQGITETQYF,TRAV3*01,TRBV27*01,TRAJ10*01,TRBJ2-5*01,GILGFVFTL,35.0,HLA-A*02:01
4,CATEDNDMRF,CASSFSDTQYF,TRAV17*01,TRBV5-4*01,TRAJ43*01,TRBJ2-3*01,YVLDHLIVV,39.0,HLA-A*02:01
...,...,...,...,...,...,...,...,...,...
633,CAASEPTGTASKLTF,CASSSPLGYTF,TRAV29/DV5*01,TRBV28*01,TRAJ44*01,TRBJ1-2*01,LTDEMIAQY,19818.0,HLA-A*01:01
634,CSNNAGNMLTF,CASGQAPNQPQHF,TRAV5*01,TRBV27*01,TRAJ39*01,TRBJ1-5*01,LTDEMIAQY,19902.0,HLA-A*01:01
635,CAPQARSARQLTF,CASRVNSNYGYTF,TRAV8-1*01,TRBV27*01,TRAJ22*01,TRBJ1-2*01,NYNYLYRLF,19924.0,HLA-A*24:02
636,CALSGGYNKLIF,CASSTPTGTENNEQFF,TRAV8-6*01,TRBV7-9*01,TRAJ4*01,TRBJ2-1*01,NYNYLYRLF,19980.0,HLA-A*24:02
637,CAGPYNNAGNMLTF,CASSLSRGFPYEQYF,TRAV25*01,TRBV27*01,TRAJ39*01,TRBJ2-7*01,LTDEMIAQY,20205.0,HLA-A*01:01

In [7]:
df_mutation = pd.read_csv(path_mutations, index_col=0)
df_mutation.head()

,Epitope,TCR,Activation Score,Label,MHC,CDR3_alpha,CDR3_beta,V_alpha,J_alpha,V_beta,J_beta,dataset
0,VPSVWRSSL,R21,76.687898,1,HLA-B*07:02,CALGTYGNNRLAF,CASTKGGPSSYEQYF,TRAV19*01,TRAJ7*01,TRBV6-6*02,TRBJ2-7*01,tumor
1,RPSVWRSSL,R21,40.891720,0,HLA-B*07:02,CALGTYGNNRLAF,CASTKGGPSSYEQYF,TRAV19*01,TRAJ7*01,TRBV6-6*02,TRBJ2-7*01,tumor
2,APSVWRSSL,R21,1.522293,0,HLA-B*07:02,CALGTYGNNRLAF,CASTKGGPSSYEQYF,TRAV19*01,TRAJ7*01,TRBV6-6*02,TRBJ2-7*01,tumor
3,SPSVWRSSL,R21,4.955414,0,HLA-B*07:02,CALGTYGNNRLAF,CASTKGGPSSYEQYF,TRAV19*01,TRAJ7*01,TRBV6-6*02,TRBJ2-7*01,tumor
4,KPSVWRSSL,R21,1.248408,0,HLA-B*07:02,CALGTYGNNRLAF,CASTKGGPSSYEQYF,TRAV19*01,TRAJ7*01,TRBV6-6*02,TRBJ2-7*01,tumor

## Databases

In [8]:
path_iedb = '../data/external/iedb_2808.csv'
path_vdjdb = '../data/external/vdjdb_2808.csv'
path_mcpas = '../data/external/mcpas_2808.csv'

In [9]:
df_iedb = pd.read_csv(path_iedb, index_col=0)
df_iedb.head()

,IR_VJ_1_v_call,IR_VJ_1_j_call,IR_VDJ_1_v_call,IR_VDJ_1_j_call,IR_VJ_1_junction_aa,IR_VDJ_1_junction_aa,organism_alpha,organism_beta,epitope,species
0,TRAV26-1*01,TRAJ37*01,TRBV14*01,TRBJ2-3*01,CIVVRSSNTGKLIF,CASSQDRDTQYF,Homo sapiens,Homo sapiens,VMAPRTLIL,Homo sapiens
1,TRAV26-1*01,TRAJ37*01,TRBV14*01,TRBJ2-3*01,CIVVRSSNTGKLIF,CASSQDRDTQYF,Homo sapiens,Homo sapiens,VMAPRTLIL,Homo sapiens
2,NaN,NaN,TRBV7-8*01,TRBJ2-7*01,NaN,CASSLGQAYEQYF,Homo sapiens,Homo sapiens,FLRGRFYGL,Homo sapiens
3,NaN,NaN,TRBV7-8*01,TRBJ2-7*01,NaN,CASSLGQAYEQYF,Homo sapiens,Homo sapiens,FLRGRAYGL,Homo sapiens
4,NaN,NaN,TRBV7-8*01,TRBJ2-7*01,NaN,CASSLGQAYEQYF,Homo sapiens,Homo sapiens,FLRGRAYGL,Homo sapiens

In [53]:
df_vdjdb = pd.read_csv(path_vdjdb, index_col=0)
df_vdjdb = df_vdjdb.rename(columns={'antigen.epitope': 'epitope'})
df_vdjdb.head()

,IR_VJ_1_junction_aa,IR_VJ_1_v_call,IR_VJ_1_j_call,IR_VDJ_1_junction_aa,IR_VDJ_1_v_call,IR_VDJ_1_j_call,epitope,species
8,NaN,NaN,NaN,CASSPRRYNEQFF,TRBV9*01,TRBJ2-1*01,HPVGEADYFEY,HomoSapiens
9,NaN,NaN,NaN,CASSGITSGEYTIYF,TRBV9*01,TRBJ1-3*01,HPVGEADYFEY,HomoSapiens
16,NaN,NaN,NaN,CASSARTGELFF,TRBV9*01,TRBJ2-2*01,HPVGEADYFEY,HomoSapiens
21,NaN,NaN,NaN,CASSVRTGELFF,TRBV9*01,TRBJ2-2*01,HPVGEADYFEY,HomoSapiens
24,NaN,NaN,NaN,CASSVRSGELFF,TRBV9*01,TRBJ2-2*01,HPVGEADYFEY,HomoSapiens

In [11]:
df_mcpas = pd.read_csv(path_mcpas, index_col=0)
df_mcpas.head()

,IR_VJ_1_v_call,IR_VJ_1_j_call,IR_VDJ_1_v_call,IR_VDJ_1_j_call,IR_VJ_1_junction_aa,IR_VDJ_1_junction_aa,epitope,species
0,NaN,NaN,TRBV8-1,TRBJ1-1,NaN,CASSDAGANTEVF,IKAVYNFATCG,Mus musculus
1,NaN,NaN,TRBV8-1,TRBJ2-1,NaN,CASSDAGAYAEQF,IKAVYNFATCG,Mus musculus
2,NaN,NaN,TRBV8-3,TRBJ1-1,NaN,CASSDAGGAAEVF,IKAVYNFATCG,Mus musculus
3,NaN,NaN,TRBV8-1,TRBJ1-6,NaN,CASSDAGHSPLYF,IKAVYNFATCG,Mus musculus
4,NaN,NaN,TRBV8-3,TRBJ2-6,NaN,CASSDAWGGAEQYF,IKAVYNFATCG,Mus musculus

# Overlap to Mutation Dataset
Here, the combination of base receptor and epitope may be in the dataset, but not any mutations.

In [34]:
base_epitopes = ['NLVPMVATV', 'VPSVWRSSL']

In [40]:
tmp = df_iedb[df_iedb['IR_VDJ_1_junction_aa'].isin(df_mutation['CDR3_beta'])
             & (~df_iedb['epitope'].isin(base_epitopes))]
tmp

Empty DataFrame
Columns: [IR_VJ_1_v_call, IR_VJ_1_j_call, IR_VDJ_1_v_call, IR_VDJ_1_j_call, IR_VJ_1_junction_aa, IR_VDJ_1_junction_aa, organism_alpha, organism_beta, epitope, species]
Index: []

In [54]:
tmp = df_vdjdb[df_vdjdb['IR_VDJ_1_junction_aa'].isin(df_mutation['CDR3_beta'])
              & (~df_vdjdb['epitope'].isin(base_epitopes))]
tmp

Empty DataFrame
Columns: [IR_VJ_1_junction_aa, IR_VJ_1_v_call, IR_VJ_1_j_call, IR_VDJ_1_junction_aa, IR_VDJ_1_v_call, IR_VDJ_1_j_call, epitope, species]
Index: []

In [41]:
tmp = df_mcpas[df_mcpas['IR_VDJ_1_junction_aa'].isin(df_mutation['CDR3_beta'])
               & (~df_mcpas['epitope'].isin(base_epitopes))]
tmp

,IR_VJ_1_v_call,IR_VJ_1_j_call,IR_VDJ_1_v_call,IR_VDJ_1_j_call,IR_VJ_1_junction_aa,IR_VDJ_1_junction_aa,epitope,species
7232,TRAV35:01,TRAJ5-01,TRBV1-01,TRBJ1-2:01,CAGPMKTSYDKVIF,CASSSANYGYTF,GILGFVFTL,Homo sapiens

We observe no overlap of the CDR3 beta chain to any relevant epitopes in the databases. Only the base epitopes or unrelated epitopes.

# Overlap to Viral Epitopes

In [79]:
ovlp_iedb = df_iedb[df_iedb['IR_VDJ_1_junction_aa'].isin(df_viral['CDR3_beta'])
             & df_iedb['epitope'].isin(df_viral['Epitope'])]
ovlp_iedb = ovlp_iedb.drop_duplicates(['IR_VDJ_1_junction_aa', 'epitope'])
print(len(ovlp_iedb))
ovlp_iedb

0

Empty DataFrame
Columns: [IR_VJ_1_v_call, IR_VJ_1_j_call, IR_VDJ_1_v_call, IR_VDJ_1_j_call, IR_VJ_1_junction_aa, IR_VDJ_1_junction_aa, organism_alpha, organism_beta, epitope, species]
Index: []

In [80]:
ovlp_vdjdb = df_vdjdb[df_vdjdb['IR_VDJ_1_junction_aa'].isin(df_viral['CDR3_beta'])
              & df_vdjdb['epitope'].isin(df_viral['Epitope'])]
ovlp_vdjdb = ovlp_vdjdb.drop_duplicates(['IR_VDJ_1_junction_aa', 'epitope'])
print(len(ovlp_vdjdb))
ovlp_vdjdb

0

Empty DataFrame
Columns: [IR_VJ_1_junction_aa, IR_VJ_1_v_call, IR_VJ_1_j_call, IR_VDJ_1_junction_aa, IR_VDJ_1_v_call, IR_VDJ_1_j_call, epitope, species]
Index: []

In [81]:
ovlp_mcpas = df_mcpas[df_mcpas['IR_VDJ_1_junction_aa'].isin(df_viral['CDR3_beta'])
              & df_mcpas['epitope'].isin(df_viral['Epitope'])]
ovlp_mcpas = ovlp_mcpas.drop_duplicates(['IR_VDJ_1_junction_aa', 'epitope'])
print(len(ovlp_mcpas))
ovlp_mcpas

0

Empty DataFrame
Columns: [IR_VJ_1_v_call, IR_VJ_1_j_call, IR_VDJ_1_v_call, IR_VDJ_1_j_call, IR_VJ_1_junction_aa, IR_VDJ_1_junction_aa, epitope, species]
Index: []